// Admin authentication helpers.
//
// The admin password is never stored or shipped in plain text. The build
// only contains a salted PBKDF2-SHA256 hash (600,000 iterations, the OWASP
// Password Storage Cheat Sheet recommendation), generated by
// `npm run set-admin-password`. Login attempts are throttled with an
// escalating lockout, and comparisons are constant-time.

import { ADMIN } from "../config.js";
import { loadGuard, saveGuard } from "./storage.js";

const PASSWORD_HASH = import.meta.env.VITE_ADMIN_PASSWORD_HASH || "";
const MAX_PASSWORD_LENGTH = 256; // stop very long inputs from tying up PBKDF2

function b64ToBytes(b64) {
  const bin = atob(b64);
  return Uint8Array.from(bin, (c) => c.charCodeAt(0));
}

export function parseHash(stored) {
  const parts = String(stored || "").split(":");
  if (parts.length !== 4 || parts[0] !== "pbkdf2-sha256") return null;
  const iterations = Number(parts[1]);
  if (!Number.isInteger(iterations) || iterations < 100_000 || iterations > 5_000_000) return null;
  try {
    const salt = b64ToBytes(parts[2]);
    const hash = b64ToBytes(parts[3]);
    if (salt.length < 16 || hash.length < 32) return null;
    return { iterations, salt, hash };
  } catch {
    return null;
  }
}

export function isAdminConfigured() {
  return parseHash(PASSWORD_HASH) !== null;
}

function timingSafeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

export async function verifyPassword(password) {
  const parsed = parseHash(PASSWORD_HASH);
  if (!parsed || typeof password !== "string" || !password || password.length > MAX_PASSWORD_LENGTH) return false;
  if (!window.crypto?.subtle) throw new Error("Secure context required (use https or localhost).");
  const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", hash: "SHA-256", salt: parsed.salt, iterations: parsed.iterations },
    key,
    parsed.hash.length * 8
  );
  return timingSafeEqual(new Uint8Array(bits), parsed.hash);
}

// ── Brute-force protection ─────────────────────────────────────

export function lockRemainingMs() {
  return Math.max(0, loadGuard().lockedUntil - Date.now());
}

export function recordFailedLogin() {
  const g = loadGuard();
  const fails = g.fails + 1;
  let lockedUntil = g.lockedUntil;
  if (fails % ADMIN.maxAttempts === 0) {
    // 5 min, then 10, 20, 40 … capped at 1 hour.
    const round = fails / ADMIN.maxAttempts;
    const minutes = Math.min(60, ADMIN.lockoutMinutes * 2 ** (round - 1));
    lockedUntil = Date.now() + minutes * 60_000;
  }
  saveGuard({ fails, lockedUntil });
  return { fails, attemptsLeft: ADMIN.maxAttempts - (fails % ADMIN.maxAttempts), lockedMs: Math.max(0, lockedUntil - Date.now()) };
}

export function clearFailedLogins() {
  saveGuard({ fails: 0, lockedUntil: 0 });
}
